name: Daily email

# Controls when the workflow will run
on:
  schedule:
    - cron:  '30 5 * * *' # https://crontab.guru/#30_5_*_*_*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install requests python-dateutil
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Decode secrets
        env: 
          TOKENS_PY_FILE: ${{ secrets.TOKENS_PY_FILE }}
        run: echo $TOKENS_PY_FILE | base64 -d > dailyEmail/tokens.py
  
      - name: Run todays-schedule-email.py script
        run: python dailyEmail/todays-schedule-email.py
